cc_binary(
    name = "memtable",
    srcs = ["testmemtable.cpp"],
    deps = [
        "//src/db:db",
        "//src/util:util",
    ],
)

cc_binary(
    name = "bloom",
    srcs = ["testbloom.cpp"],
    deps = [
        "//src/util:bloom",
    ],
)