
cc_library(
    name = "db",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
         "//src/util:util",
         "@snappy",
    ],
)
