SKIPLIST_HEADERS = glob([
        "skiplist/include/*.h",
])
SKIPLIST_SOURCES = glob([
        "skiplist/src/*.cpp",
])
cc_library(
    name = "skiplist",
    hdrs = SKIPLIST_HEADERS,
    srcs = SKIPLIST_SOURCES,
    visibility = ["//visibility:public"],
)